language: node_js
node_js: "12.16.1"
cache: yarn

services:
  - docker

install:
  - docker-compose -f packages/api/docker-compose.yml up --build -d
  - yarn set version berry
  - yarn --frozen-lockfile
  - yarn migration:up

jobs:
  include:
    - stage: "API"
      name: "Yarn Test"
      script: "yarn test"
    - name: "Yarn Lint"
      script: "yarn lint"
