language: node_js
node_js:
  - "node"

services:
  - docker

install:
  - docker-compose -f packages/api/docker-compose.yml up --build -d
  - yarn
  - yarn migration:up

jobs:
  include:
    - stage: "API"
      name: "Yarn Test"
      script: "yarn test"
    - name: "Yarn Lint"
      script: "yarn lint"
