language: node_js
node_js:
  - "node"

services:
  - docker

install:
  - docker-compose -f packages/api/docker-compose.yml up --build -d
  - npm ci
  - npx lerna bootstrap --hoist --ignore pi-service
  - npm run migration:up

jobs:
  include:
    - stage: "API"
      name: "NPM Test"
      script: "npm run test"
    - name: "NPM Lint"
      script: "npm run lint"
