language: node_js
node_js:
  - "node"

services:
  - docker

install:
  - npm ci
  - npx lerna bootstrap --hoist
  - cd packages/api/api-v1
  - docker-compose up --build -d
  - npm run migration up

jobs:
  include:
    - stage: "API"
      name: "NPM Test"
      script: "npm run test"
    - name: "NPM Lint"
      script: "npm run lint"
