language: node_js
node_js: "13.13.0"
cache:
  directories:
    - .yarn/cache
env:
  global:
    # so the yarn installed in before_install will be used
    - PATH=$HOME/.yarn/bin:$PATH
services:
  - docker
matrix:
  fast_finish: true
before_install:
  # update yarn - travis is using an old version
  # https://yarnpkg.com/en/docs/install#alternatives-stable
  - curl -o- -L https://yarnpkg.com/install.sh | bash
install:
  - docker-compose -f packages/api/docker-compose.yml up --build -d
  - yarn
  - yarn migration:up
script:
  - yarn test
  - yarn lint
