version: '3.7'

services:
  postgres:
    container_name: 'postgres'
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "iot-api"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "iot"
    ports:
      - "5432:5432"
