// This file is automatically generated from your CSS. Any edits will be overwritten.
export const loginPage: string;
export const card: string;
export const layeredBackground: string;
export const error: string;
